In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.io.wavfile as wav
from scipy import interpolate
from scipy import signal
from IPython.display import Audio

In [2]:
music_rate, music_signal = wav.read('music.wav')
voice_rate, voice_signal = wav.read('sound.wav')
noise_1_rate, noise_1 = wav.read('noise1.wav')
noise_2_rate, noise_2 = wav.read('noise2.wav')
noise_3_rate, noise_3 = wav.read('noise3.wav')


In [3]:
def get_variance(snr, signal, noise):
    """
    Function that computes the required variance of the noise to achieve a given SNR.
    """
    #get the norm of the signal and the noise
    norm = np.linalg.norm(signal)**2
    noise_norm = np.linalg.norm(noise)**2
    #compute the variance
    variance = norm/(noise_norm*(np.exp(snr/10)))
    #variance = norm/(noise_norm*(10**(snr/10)))
    return variance

In [37]:
# sound_signal = voice_signal
# sound_rate = voice_rate
sound_signal = music_signal
sound_rate = music_rate
noise = noise_2
#sample a vector of the same size as the signal from the noise
noise = np.random.choice(noise, len(sound_signal), replace=True)
target_snr = 50
variance = get_variance(target_snr, sound_signal, noise)
noisy_signal = sound_signal + noise * np.sqrt(variance)

snr = 10*np.log(np.linalg.norm(sound_signal)**2/np.linalg.norm(noisy_signal-sound_signal)**2)

print("Target SNR: ", target_snr)
print('SNR: ', snr)
print('Variance: ', variance)

Target SNR:  50
SNR:  50.0
Variance:  0.006704926415565825


In [38]:
#display noisy signal audio object
Audio(noisy_signal, rate=music_rate)

$ stft(X) = stft(Y)(1-\frac{lambda^2 * |stft(S)|^2}{|stft(Y)|^2})^+ $

In [53]:
def spectral_subtraction(noisy_signal, sample_rate, noise, λ, α, β, γ):
    """ 
    Function that removes the noise from a noisy signal using spectral subtraction.
    """
    mask = np.zeros(len(noisy_signal))
    Y_abs = np.abs(np.fft.fft(noisy_signal))
    S_abs = np.abs(np.fft.fft(noise))
    #if Y_abs**a > S_abs**b then mask = 1
    mask = np.where(Y_abs**α > λ*S_abs**α, 1, 0)
    value_1 = 
    return psd_signal

In [55]:
#spectral denoise
λ = 1
psd_signal = spectral_subtraction(noisy_signal, sound_rate, noise, λ)
#inverse the stft
_, denoised_signal = signal.istft(psd_signal, sound_rate, nperseg=1024)
#display denoised signal audio object
Audio(denoised_signal, rate=music_rate)

In [17]:
#display noisy signal audio object
Audio(noisy_signal, rate=music_rate)

In [ ]:
#display spectrogram
plt.pcolormesh(t, f, np.abs(Zxx), vmax=1000)
plt.title('STFT Magnitude')
plt.ylabel('Frequency [Hz]')
plt.xlabel('Time [sec]')
plt.show()


In [48]:
find_index = stft_signal[:,10].max()

#get index with max value
index_max = np.where(stft_signal[:,10] == find_index)
#compute the frequency of the max value
frequency_max = frequencies[index_max]
frequency_max

array([14451.61290323])

In [12]:
gabor_transform_signal.shape

(1024, 269)

In [13]:
noisy_signal.shape

(139200,)

In [20]:
gabor_transform_signal[:,10]

array([ 636.07161234,  387.6588234 ,  -73.26516961, ...,  466.10004655,
        668.23344877, -559.49752737])

In [21]:
noisy_signal[512*10:512*10+1024]

array([ 636.07161234,  387.6588234 ,  -73.26516961, ...,  466.10004655,
        668.23344877, -559.49752737])

In [59]:
x = np.asarray([1,2,-3])
norm_1 = np.linalg.norm(x)**2
print(norm_1)
norm_2 = np.abs(x[0])**2 + np.abs(x[1])**2 + np.abs(x[2])**2
print(norm_2)

14.0
14


old attempt at stft

In [ ]:
#gabor transform of the signal
def gabor_transform(signal, window_size, hop_size):
    """
    Function that computes the gabor transform of the signal.
    """
    #compute the number of frames
    num_frames = int(np.floor((len(signal)-window_size)/hop_size))
    #initialize the gabor transform matrix
    gabor_transform = np.zeros((window_size, num_frames))
    #compute the gabor transform
    for i in range(num_frames):
        gabor_transform[:,i] = signal[i*hop_size:i*hop_size+window_size]
    return gabor_transform

#compute stft given a gabor transform
def stft(gabor_transform):
    """
    Function that computes the stft given a gabor transform.
    """
    #get the window size
    window_size = gabor_transform.shape[0]
    #get the number of frames
    num_frames = gabor_transform.shape[1]
    #initialize the stft matrix
    stft = np.zeros((window_size, num_frames), dtype=complex)
    #compute the stft
    for i in range(num_frames):
        stft[:,i] = np.fft.fft(gabor_transform[:,i])
    return stft

# extract frequencies and time from the stft
def get_frequencies_and_time(stft, sample_rate, hop_size):
    """
    Function that extracts the frequencies and time from the stft.
    """
    #get the window size
    window_size = stft.shape[0]
    #get the number of frames
    num_frames = stft.shape[1]
    #compute the frequencies
    frequencies = np.linspace(0, sample_rate, window_size)
    #compute the time
    time = np.linspace(0, num_frames*hop_size/sample_rate, num_frames)
    return frequencies, time

In [ ]:
#build a signal from three consecutive sine waves
consignals = np.concatenate((np.sin(np.linspace(0, 2*np.pi*1000, 10240)), np.sin(np.linspace(0, 2*np.pi*2000, 10240)), np.sin(np.linspace(0, 2*np.pi*3000, 10240))))
test_signal = consignals
test_rate = music_rate
#apply gabor transform to signal
window_size = 1024
hop_size = 512
gabor_transform_signal = gabor_transform(test_signal, window_size, hop_size)
#apply stft to gabor transform
stft_signal = stft(gabor_transform_signal)
#take only the upper half of the stft
frequencies, times = get_frequencies_and_time(stft_signal, test_rate, hop_size)
#display the stft
plt.figure(figsize=(20,10))
plt.title('STFT of the signal')
plt.pcolormesh(times, frequencies[:int(window_size/2)], np.abs(stft_signal[:int(window_size/2),:]))
plt.xlabel('time (s)')
plt.ylabel('frequency (Hz)')
plt.show()
